
import java.awt.CardLayout;
import java.awt.Container;
import javax.swing.JPanel;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author marie
 */
public class actionPanel extends javax.swing.JPanel {

    /**
     * Creates new form actionPanel
     */
    public actionPanel() {
        initComponents();
                
        //Delete the arrow icon of the internal frame
        Container pane = ((BasicInternalFrameUI) internalFrame.getUI()).getNorthPane();
        pane.remove(0);
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        internalFrame = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        menuNewFile = new javax.swing.JMenu();
        gtfMenuDisplayText = new javax.swing.JMenu();
        gtfMenuStats = new javax.swing.JMenu();
        menuLongestShortestModel = new javax.swing.JMenuItem();
        menuLongestShortestModels = new javax.swing.JMenuItem();
        menuAverageGeneLength = new javax.swing.JMenuItem();
        gtfMenuAllStats = new javax.swing.JMenuItem();
        gtfMenuExons = new javax.swing.JMenu();
        menuTextExons = new javax.swing.JMenuItem();
        menuGraphExons = new javax.swing.JMenuItem();
        menuExonsAllDisplay = new javax.swing.JMenuItem();
        fastaMenuDisplayText = new javax.swing.JMenu();
        fastaMenuStats = new javax.swing.JMenu();
        menuSequenceLen = new javax.swing.JMenuItem();
        menuGcContent = new javax.swing.JMenuItem();

        internalFrame.setBorder(null);
        internalFrame.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        internalFrame.setEnabled(false);
        internalFrame.setFocusable(false);
        internalFrame.setFrameIcon(null);
        internalFrame.setVisible(true);

        menuBar.setBorder(null);

        menuNewFile.setText("Choose new file");
        menuNewFile.setBorderPainted(true);
        menuNewFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuNewFileMouseClicked(evt);
            }
        });
        menuBar.add(menuNewFile);

        gtfMenuDisplayText.setText("Display text");
        gtfMenuDisplayText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gtfMenuDisplayTextMousePressed(evt);
            }
        });
        menuBar.add(gtfMenuDisplayText);

        gtfMenuStats.setText("gtf statistics");

        menuLongestShortestModel.setText("Average number of exons");
        menuLongestShortestModel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLongestShortestModelActionPerformed(evt);
            }
        });
        gtfMenuStats.add(menuLongestShortestModel);

        menuLongestShortestModels.setText("Longest shortest genes models");
        gtfMenuStats.add(menuLongestShortestModels);

        menuAverageGeneLength.setText("Average gene length");
        menuAverageGeneLength.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAverageGeneLengthActionPerformed(evt);
            }
        });
        gtfMenuStats.add(menuAverageGeneLength);

        gtfMenuAllStats.setText("All statistics");
        gtfMenuStats.add(gtfMenuAllStats);

        menuBar.add(gtfMenuStats);

        gtfMenuExons.setText("Exons");

        menuTextExons.setText("Display exons textually");
        gtfMenuExons.add(menuTextExons);

        menuGraphExons.setText("Display exons graphically");
        gtfMenuExons.add(menuGraphExons);

        menuExonsAllDisplay.setText("Display exons textually and graphically");
        gtfMenuExons.add(menuExonsAllDisplay);

        menuBar.add(gtfMenuExons);

        fastaMenuDisplayText.setText("Display text");
        fastaMenuDisplayText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                fastaMenuDisplayTextMousePressed(evt);
            }
        });
        menuBar.add(fastaMenuDisplayText);

        fastaMenuStats.setText("fasta statistics");

        menuSequenceLen.setText("Sequence length");
        menuSequenceLen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSequenceLenActionPerformed(evt);
            }
        });
        fastaMenuStats.add(menuSequenceLen);

        menuGcContent.setText("GC content");
        fastaMenuStats.add(menuGcContent);

        menuBar.add(fastaMenuStats);

        internalFrame.setJMenuBar(menuBar);

        javax.swing.GroupLayout internalFrameLayout = new javax.swing.GroupLayout(internalFrame.getContentPane());
        internalFrame.getContentPane().setLayout(internalFrameLayout);
        internalFrameLayout.setHorizontalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        internalFrameLayout.setVerticalGroup(
            internalFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(internalFrame)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(internalFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void menuLongestShortestModelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLongestShortestModelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuLongestShortestModelActionPerformed

    private void menuAverageGeneLengthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAverageGeneLengthActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAverageGeneLengthActionPerformed

    private void menuSequenceLenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSequenceLenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuSequenceLenActionPerformed

    private void gtfMenuDisplayTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gtfMenuDisplayTextMousePressed
        //Display table, not text result
        mainFrame.displayResultsPane.setPanelVisible(false);
        
        mainFrame.displayResultsPane.displayTable(mainFrame.displayResultsPane.contentToString(mainFrame.fileChooserPanel.getFileContent().get(7)));
    }//GEN-LAST:event_gtfMenuDisplayTextMousePressed

    private void fastaMenuDisplayTextMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fastaMenuDisplayTextMousePressed
        //Display text result
        mainFrame.displayResultsPane.setPanelVisible(true);
        
        //Opening on the first page
        mainFrame.displayResultsPane.setPageNumber(0);
        
        //Do not display next button if maximal number of pages equal 0
        if(mainFrame.displayResultsPane.maxNumberPages(mainFrame.fileChooserPanel.getFileContent()) == 0){
            mainFrame.displayResultsPane.setNextBtnVisible(false);
        }
        
        //Do not display previous button
        mainFrame.displayResultsPane.setPreviousBtnVisible(false);
        
        //Display content of fasta file, accessible from fileChooserPane
        mainFrame.displayResultsPane.displayText(mainFrame.fileChooserPanel.getFileContent(), 0);
    }//GEN-LAST:event_fastaMenuDisplayTextMousePressed

    private void menuNewFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuNewFileMouseClicked
        // TODO add your handling code here:
        chooseNewFile();
        mainFrame.displayResultsPane.resetText();
    }//GEN-LAST:event_menuNewFileMouseClicked
    
    //Display different menu items according to the chosen file
    public static void setMenu(fileChooserPanel fileChooser){
        boolean gtf = fileChooser.getFileTypes()[0];
        boolean fasta = fileChooser.getFileTypes()[1];
        
        //Set gtf menu visible or not
        gtfMenuDisplayText.setVisible(gtf);
        gtfMenuStats.setVisible(gtf);
        gtfMenuExons.setVisible(gtf);
        
        //Set fasta menu visible or not
        fastaMenuDisplayText.setVisible(fasta);
        fastaMenuStats.setVisible(fasta); 
    }
        
    //Display information from the previous panel and the chosen file to this panel
    public static void setData(fileChooserPanel fileChooser){
        //Display message of which file was chosen
        internalFrame.setTitle(fileChooser.getFileChosenMessage());
        setMenu(fileChooser);
    }
    
    public void chooseNewFile(){
        mainFrame.fileChooserPanel.setWaitMessage("");
        //Bring the fileChooserPanel back
        this.setVisible(false);
        //Set displayResultPanel to false
        mainFrame.displayResultsPane.setVisible(false);
        mainFrame.fileChooserPanel.setVisible(true);
    }
    
    //Make a new panel visible in th existing dataframe
    private void openNewPanel(JPanel pane){
        //Open new panel
        pane.setVisible(true); 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JMenu fastaMenuDisplayText;
    private static javax.swing.JMenu fastaMenuStats;
    private javax.swing.JMenuItem gtfMenuAllStats;
    private static javax.swing.JMenu gtfMenuDisplayText;
    private static javax.swing.JMenu gtfMenuExons;
    private static javax.swing.JMenu gtfMenuStats;
    private static javax.swing.JInternalFrame internalFrame;
    private javax.swing.JMenuItem menuAverageGeneLength;
    private static javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem menuExonsAllDisplay;
    private javax.swing.JMenuItem menuGcContent;
    private javax.swing.JMenuItem menuGraphExons;
    private javax.swing.JMenuItem menuLongestShortestModel;
    private javax.swing.JMenuItem menuLongestShortestModels;
    private javax.swing.JMenu menuNewFile;
    private javax.swing.JMenuItem menuSequenceLen;
    private javax.swing.JMenuItem menuTextExons;
    // End of variables declaration//GEN-END:variables
}
