
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author marie
 */
public class exonsPanel extends javax.swing.JPanel {

    /**
     * Creates new form exonsPanel
     */
    public exonsPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        textExons = new javax.swing.JScrollPane();
        jTextPane = new javax.swing.JTextPane();
        graphicExons = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        secondFileChooser = new secondFileChooserPanel(this);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        textExons.setViewportView(jTextPane);

        jLayeredPane1.setLayer(textExons, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(textExons, "textual");

        graphicExons.setBackground(new java.awt.Color(204, 0, 204));

        label1.setText("graphic");

        javax.swing.GroupLayout graphicExonsLayout = new javax.swing.GroupLayout(graphicExons);
        graphicExons.setLayout(graphicExonsLayout);
        graphicExonsLayout.setHorizontalGroup(
            graphicExonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        graphicExonsLayout.setVerticalGroup(
            graphicExonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(graphicExons, javax.swing.JLayeredPane.PALETTE_LAYER);
        jLayeredPane1.add(graphicExons, "graphical");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(secondFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(secondFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    public void fileChoiceVisibility(boolean choice) {
        if (choice) {
            secondFileChooser.setVisible(true);
        }
        jLayeredPane1.setVisible(false);
    }

    public void changeCardPanel(String cardName) {
        CardLayout card = (CardLayout) this.jLayeredPane1.getLayout();
        card.show(this.jLayeredPane1, cardName);
    }

    public void textExons(int[][] offsetLength){
        /*
        jTextPane.setContentType("text/html"); //The content type is html
        String message = "<font color = 'red'> Hellos it's me </font>" + "<font color = 'blue'> MARIE </font>";
        jTextPane.setText(message);
        */
        
        String message = "Hello cest moi Marie et je veux changer la couleur des exons!!!";
        jTextPane.setText(message);
        //Creat attribute set to change color
        SimpleAttributeSet attributes = new SimpleAttributeSet();
        StyleConstants.setForeground(attributes, Color.cyan);
        
        //Apply to some parts of text
        StyledDocument styleDoc = jTextPane.getStyledDocument();
        for(int row = 0; row < offsetLength.length; row++){
            styleDoc.setCharacterAttributes(offsetLength[row][0], offsetLength[row][0], attributes, false);
        }
        //styleDoc.setCharacterAttributes(1, 5, attributes, false);
        //styleDoc.setCharacterAttributes(15, 3, attributes, false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel graphicExons;
    public javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JTextPane jTextPane;
    private java.awt.Label label1;
    public secondFileChooserPanel secondFileChooser;
    private javax.swing.JScrollPane textExons;
    // End of variables declaration//GEN-END:variables
}
