/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author marie
 */
import java.awt.Graphics;
import java.awt.Color;
import java.awt.Dimension;
import java.util.ArrayList;


public class graphicExons extends javax.swing.JPanel{

    /**
     * Creates new form graphicExons
     */
    public graphicExons() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        annotationLbl = new javax.swing.JLabel();

        annotationLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(annotationLbl, javax.swing.GroupLayout.DEFAULT_SIZE, 964, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(annotationLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(404, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Create instance of class exons
    private exons classExons = new exons();
    private int[][] coordinates;
    private int[] lineCoordinates;
    private String[] fastaAnnotation;
    
    
    
    //Override paint component
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g); //Render lightweigth components
        
        Color exonColor = new Color(255, 127, 80);
        //Set color and rectangles
        g.setColor(exonColor);
        
        //New instance of exons to call function that gives rectangles coordinates
        exons exons = new exons();
        //Array list with the coordinates of each sequence
        ArrayList<int[]> allCoordinates = new ArrayList<int[]>();
        allCoordinates = exons.exonsGraphical(coordinates, this.getSize().height, this.getSize().width);
        
        //For every set of coordinate, draw a ractangle
        for(int i= 0; i < allCoordinates.size(); i++){
            int[] rectDimensions = allCoordinates.get(i);
            
            //Fill rectangle
            g.fillRect(rectDimensions[0], rectDimensions[1], rectDimensions[2], rectDimensions[3]);
        }
        
        //Coordinate of line between exons
        ArrayList<int[]> linesCoord = exons.lineCoordinates(fastaAnnotation, this.getSize().width);
        //Draw a line between all exons
        for(int i = 0; i < linesCoord.size(); i++){
            g.fillRect(linesCoord.get(i)[0], linesCoord.get(i)[1], linesCoord.get(i)[2], linesCoord.get(i)[3]);
        }
    }
    
    public void setCoordinates(int[][] newCoordinates){
        coordinates = newCoordinates;
        lineCoordinates = lineCoordinates;
    }
    
    public void setAnnotation(String[] annotation){
        fastaAnnotation = annotation;
        String message = fastaAnnotation[0] + ":" + fastaAnnotation[1] + "-" + fastaAnnotation[2];
        annotationLbl.setText(message);
        annotationLbl.setVisible(true);
        repaint();
        System.out.println(message);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel annotationLbl;
    // End of variables declaration//GEN-END:variables
}
